/*--------------------------------------------------------------------------------------+
|
|     $Source: ITwinMetadataConstants.h $
|
|  $Copyright: (c) 2025 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/

#pragma once

namespace ITwinCesium::Metada
{
	//-----------------------------------------------------------------------------------
	// The following constants are found in the meta-data properties generated by the
	// iTwin Mesh Export Service
	//-----------------------------------------------------------------------------------

	// default slot used for Bentley MeshFeature (element/model/subcategory)
	// this corresponds to _FEATURE_ID_0 meta-data attribute
	static const int64 ELEMENT_FEATURE_ID_SLOT = 0;

	static const FString ELEMENT_NAME		= TEXT("element");
	static const FString MODEL_NAME			= TEXT("model");
	static const FString SUBCATEGORY_NAME	= TEXT("subcategory");
	static const FString GEOMETRYCLASS_NAME = TEXT("geometryClass");

	// material IDs are about to be added in Cesium Mesh-Export, in a separate table
	static const int64 MATERIAL_FEATURE_ID_SLOT = 1;
	static const FString MATERIAL_NAME		= TEXT("material");
}
