/*--------------------------------------------------------------------------------------+
|
|     $Source: ITwinMetadataConstants.h $
|
|  $Copyright: (c) 2024 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/

#pragma once

namespace ITwinCesium::Metada
{

	// those constants are found in the meta-data properties generated by the
	// iTwin Mesh Export Service

	static const FString ELEMENT_NAME		= TEXT("element");
	static const FString MODEL_NAME			= TEXT("model");
	static const FString SUBCATEGORY_NAME	= TEXT("subcategory");
}
